export const CATEGORY_ERROR_CODES = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  NAME_INVALID: 'CATEGORY_NAME_INVALID',
  NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  NAME_TOO_LONG: 'CATEGORY_NAME_TOO_LONG',
};
