export const ORDER_ERROR_CODES = {
  PRODUCT_INVALID: 'PRODUCT_INVALID',
  QUANTITY_INVALID: 'QUANTITY_INVALID',
  ORDER_DETAILS_INVALID: 'ORDER_DETAILS_INVALID',
  SOME_PRODUCTS_NOT_FOUND: 'SOME_PRODUCTS_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
};
