export const PRODUCT_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  NAME_INVALID: 'PRODUCT_NAME_INVALID',
  NAME_ALREADY_EXISTS: 'PRODUCT_NAME_ALREADY_EXISTS',
  NAME_TOO_LONG: 'PRODUCT_NAME_TOO_LONG',
  DESCRIPTION_INVALID: 'PRODUCT_DESCRIPTION_INVALID',
  PRICE_INVALID: 'PRODUCT_PRICE_INVALID',
  STATUS_INVALID: 'PRODUCT_STATUS_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CATEGORY_INVALID: 'CATEGORY_INVALID',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
};
