export const USER_ERROR_CODES = {
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_LOWERCASE_REQUIRED: 'PASSWORD_LOWERCASE_REQUIRED',
  PASSWORD_UPPERCASE_REQUIRED: 'PASSWORD_UPPERCASE_REQUIRED',
  PASSWORD_NUMBER_REQUIRED: 'PASSWORD_NUMBER_REQUIRED',
  PASSWORD_SPECIAL_CHAR_REQUIRED: 'PASSWORD_SPECIAL_CHAR_REQUIRED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  NAME_INVALID: 'NAME_INVALID',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  EMAIL_TOO_LONG: 'EMAIL_TOO_LONG',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
};
